algoritmo "Exercicio 5"
// Função : Portugol
// Autor :  Eduardo
// Data : 27/4/2017
// Descritivo: Par ou Impar
// Seção de Declarações
var a :inteiro

inicio
      repita
               escreva ("digite seu numero: ")
               leia (a)
               se a mod 2 = 0 entao
                  escreval ("par ")
                  senao
                  escreval ("impar ")
               fimse
      ate a = -1
fimalgoritmo
